import type { Metadata } from "next";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Porridge",
  description: "Generated by FoM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      > */}
      <body>{children}</body>
      {/* </ThemeProvider> */}
    </html>
  );
}
